version: "3.9"

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django:

    build:
      context: .
      dockerfile: Dockerfile
      
    
    ports:
      - '8000:8000'
    
    volumes:
      - ./code:/code
    
    depends_on: 
      - db
    

  
  